import { describe, expect, it } from "vitest";
import { countShots, extractSection, firstHeading, readySummary } from "./proposalMarkdown";

/* A trimmed but structurally faithful copy of a real proposal —
   ReelScraper/studio/instagram/2026-07-19-similar-a-young-south-asian-man-…md.
   The heading levels, the `### Shot N — …` shape and the `## Audio` bullet
   shape are verbatim, because that shape is exactly what these readers parse. */
const PROPOSAL = `# Clone recipe — A young South Asian man showcases three stylish date night outfits in a quick-cut fashion reel.

> Generated by the demo (\`scripts/demo.sh\`) as a **clone** recipe for the **similar-content** producer.

## Why this one (easy-to-make best)
- **virality_score:** 99.3   **tier:** Viral
- **shots:** 4   **duration:** 32.2s

## Shot list (generation-ready prompts)
### Shot 1 — 8s · Static
- A young South Asian man stands against a dark marbled wall.
- **On-screen text:** 3 DATE OUTFITS 👕

### Shot 2 — 7.8s · Static
- The man is now wearing a light blue linen long-sleeve shirt.
- **On-screen text:** 1

### Shot 3 — 6s · Static
- **On-screen text:** 2

### Shot 4 — 10.4s · Static
- **On-screen text:** 3

## Audio

- **Sound:** Long Way Home (From "Night Shift Vol 2") [Remix] — Ada Vance
- **Music:** An upbeat and modern Tamil pop/film song with a strong beat.
- **Audio type:** trending_sound_led
- **Reuse:** reuse_original
- **Sound page:** https://www.instagram.com/reels/audio/1000000000000002/

## Rendered media (generated)

- **Video:** \`SimilarContent/assets/slug/reel.mp4\` — 32.2s · 4 frame(s) · 1080×1920 (9:16) · silent
`;

describe("firstHeading", () => {
  it("returns the first h1-h3 heading text without the hashes", () => {
    expect(firstHeading(PROPOSAL)).toBe(
      "Clone recipe — A young South Asian man showcases three stylish date night outfits in a quick-cut fashion reel.",
    );
  });

  it("returns null when the body carries no heading", () => {
    expect(firstHeading("just a paragraph\nand another")).toBeNull();
  });

  it("ignores h4+ so a deep sub-heading never becomes a card title", () => {
    expect(firstHeading("#### deep\n\n## real")).toBe("real");
  });
});

describe("extractSection", () => {
  it("lifts the ## Audio block and stops at the next same-level heading", () => {
    const audio = extractSection(PROPOSAL, "Audio");
    expect(audio).not.toBeNull();
    expect(audio!.startsWith("## Audio")).toBe(true);
    expect(audio).toContain("**Reuse:** reuse_original");
    expect(audio).toContain("reels/audio/1000000000000002");
    // must NOT bleed into the following section
    expect(audio).not.toContain("Rendered media");
  });

  it("keeps deeper sub-headings inside the section", () => {
    const shots = extractSection(PROPOSAL, "Shot list");
    expect(shots).toContain("### Shot 4");
    expect(shots).not.toContain("## Audio");
  });

  it("matches by prefix, case-insensitively", () => {
    expect(extractSection(PROPOSAL, "audio")).toContain("**Sound:**");
  });

  it("returns null for an absent section", () => {
    expect(extractSection(PROPOSAL, "Nonexistent")).toBeNull();
  });
});

describe("readySummary", () => {
  it("drops headings and markdown punctuation, keeping the first content lines", () => {
    const s = readySummary(PROPOSAL);
    expect(s).not.toContain("#");
    expect(s).not.toContain("**");
    // `_` is stripped along with the other markdown emphasis chars, so
    // `virality_score` reads as `viralityscore` — deliberate, and only ever
    // shown as a blurb, never parsed.
    expect(s).toContain("viralityscore: 99.3");
    expect(s).toContain("tier: Viral");
  });

  it("truncates long bodies with an ellipsis", () => {
    const long = Array.from({ length: 4 }, () => "x".repeat(100)).join("\n");
    const s = readySummary(long);
    expect(s.length).toBeLessThanOrEqual(241);
    expect(s.endsWith("…")).toBe(true);
  });

  it("is empty for a headings-only body", () => {
    expect(readySummary("# title\n## another")).toBe("");
  });
});

describe("countShots", () => {
  it("counts the ### Shot headings — the frame count a render will be billed for", () => {
    expect(countShots(PROPOSAL)).toBe(4);
  });

  it("does not count the shot-list heading itself", () => {
    expect(countShots("## Shot list (generation-ready prompts)\n### Shot 1 — 2s")).toBe(1);
  });

  it("returns 0 when there is no shot list", () => {
    expect(countShots("# title\n\nsome prose")).toBe(0);
  });

  it("tolerates CRLF line endings", () => {
    expect(countShots("### Shot 1 — 2s\r\n### Shot 2 — 3s\r\n")).toBe(2);
  });
});
